dml_config = {
    "match_results":
        [
            "match_type",
            "match_type_number",
            "match_date",
            "season",
            "gender",
            "event_name",
            "event_match_number",
            "team1",
            "team2",
            "venue",
            "toss_winner",
            "toss_decision",
            "winner",
            "win_by_runs",
            "win_by_wickets",
            "outcome_result",
            "outcome_method"
        ]
    ,
    "match_ball_by_ball":
        [
            "match_type",
            "match_type_number",
            "match_date",
            "batting_team",
            "fielding_team",
            "over",
            "batter",
            "bowler",
            "non_striker",
            "runs_batter",
            "runs_extras",
            "non_boundary",
            "runs_total",
            "wicket_player_out",
            "wicket_kind",
            "wicket_fielder_involved",
            "extras_byes",
            "extras_legbyes",
            "extras_noballs",
            "extras_penalty",
            "extras_wides",
            "target_overs",
            "target_runs"
        ]
    ,
    "player_universe":
        [
            "match_type",
            "match_type_number",
            "match_date",
            "team",
            "gender",
            "name",
            "unique_id"
        ]
}
